world:
  timestep: 0.1
  random_seed: 10

planner:
  search_height: 30

map:
  width: 600
  length: 600
  height: 40
  building:
    x:
    - 100
    - 300
    - 250
    y:
    - 100
    - 200
    - 400
    width: 50
    length: 50
    height: 15
    floors: 3

robots:
  UAV:
    num: 5
    velocity: 20
    scout_range: 30
    theta: 40
    HFOV: 24.9
    VFOV: 14.7
    x: 250
    y: 400
    z: 30
  Target:
    num: 9
    x:
    - 50
    - 60
    - 150
    - 200
    - 250
    - 300
    - 350
    - 400
    - 450
    y:
    - 50
    - 400
    - 150
    - 450
    - 50
    - 200
    - 250
    - 350
    - 400
    z:
    - 0
    - 0
    - 13
    - 0
    - 0
    - 9
    - 11
    - 0
    - 0
